echo "gcloud run deploy $DEPLOY_PROJECT_NAME --region $DEPLOY_REGION --image $DEPLOY_IMAGE --set-env-vars BUILD_MODE=production,CORS_ALLOW_ORIGIN=$CORS_ALLOW_ORIGIN,STEAM_API_KEY=$STEAM_API_KEY
"

gcloud run deploy $DEPLOY_PROJECT_NAME --region $DEPLOY_REGION --image $DEPLOY_IMAGE --set-env-vars BUILD_MODE=production,CORS_ALLOW_ORIGIN=$CORS_ALLOW_ORIGIN,STEAM_API_KEY=$STEAM_API_KEY
