name: Test

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '**'

jobs:
  test:
    name: Unit Test
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
    - name: go test
        run: go test -race -coverprofile=coverage.out -covermode=atomic
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
